### ISSUE TITLE
Changing color system

### ISSUE THREAD

**Issue by tonitch** [wildrun0/HomeSetter#1]
A new color system will soon be adopted! I just want to warn you about it!

as soon as this https://github.com/cuberite/cuberite/pull/5416  pr is pushed, you would have to change the @'s in your code with &'s and change letters according to this color code convention ^^

![image](https://user-images.githubusercontent.com/26271060/180885268-8729a6dd-9da4-40db-b958-8430971852c7.png)

hope this is helpful ^^

**Comment by wildrun0** [comment]
ohh thanks a lot
I will keep that in mind & update plugin as soon as this pr will be pushed

**Comment by wildrun0** [comment]
added in latest release
